### ISSUE TITLE
Issues Installing

### ISSUE THREAD

**Issue by Bluemoondragon07** [rabbit19981023/yomigana-ebook#2]
Hi! Firstly, thank you so much for making this tool. I am very excited to use it!

Now, this is the first time I've attempted to install a tool like this, and I'm having some difficulty. Hopefully, they are problems with my procedure and nothing else, but I can't figure out how to convert the e-books. 

I read your instructions: 

```
$ git clone https://github.com/rabbit19981023/yomigana-ebook.git
$ pip install .
$ python -m unidic download
$ yomigana_ebook <your-ebooks>
```

In **Git CMD** I cloned the repository and successfully completed the first three steps.
But the last command is where I am stuck. 

I am assuming I am supposed to input something for `<your-ebooks>`. There is a folder `C:/Users/my-user/yomigana-ebook/Books` where I put some epubs to convert. I have tried `yomigana_ebook Books`, `yomigana_ebook /Books`, `yomigana-ebook/Books/`, `yomigana_ebook Books/`, and other variants, including the full directory path. 

Every time I get this message: `'yomigana_ebook' is not recognized as an internal or external command,
operable program or batch file.`
I added the yomigana-ebook directory to the system's PATH environment variable, also. I'm not sure if that was supposed to fix it (ChatGPT suggested it, but AI isn't super smart). 

Is there a specific format I should use for this? Could you give me an example, please? And again, thank you for creating and maintaining this tool, I can't wait to use it!

**Comment by rabbit19981023** [comment]
Hi @Bluemoondragon07 , thank you for using this tool!

Firstly, I'm sorry that I may not write the clean message how to use it. To use the tool, just pass the **file paths** (not directory path) like this:

`$ yomigana_ebook Books/novel1.epub Books/novel2.epub Books/novel3.epub ...`

However, according to the error message you provide:

`'yomigana_ebook' is not recognized as an internal or external command, operable program or batch file.`

I could assume that the OS couldn't find the executable command.

I tried the installation process and soon I found out that I made a stupid mistake, the process should be like this:

```
$ git clone https://github.com/rabbit19981023/yomigana-ebook.git
$ pip install ./yomigana-ebook  # fix this line
$ python -m unidic download
$ yomigana_ebook <your-ebooks>
```

Maybe you had noticed the problem and use the correct way to install it.

However, I can't reproduce the issue you're having by following the steps above (the fixed one). Thus I assume the problem may be the following:

1. the problem may occur on windows11. (my computer is windows10, and I have no way to test it.)

2. the python/pip version is a bit old

    **To fix: just update them to latest version**

3. the name of the executable command `yomigana_ebook` conflicts with the same-name folder in the project.

    **To fix: do not use the command `yomigana_ebook` in the project path.**

4. may the problem related to the python virtual environment (usaully it's the `.venv` folder)

    **To fix: delete the whole folder you used: `C:/Users/my-user/yomigana-ebook/` (also the python virtualenv) and try the fixed process above again.**

You could just ignore the problems above, and follow the steps below, I believe you can enjoy the tool now:

```
$ git clone https://github.com/rabbit19981023/yomigana-ebook.git
$ cd yomigana-ebook
$ pip install .
$ python -m unidic download
$ python -m yomigana_ebook.cli <your-ebooks>  # fix this line
```

Or you can just use `dockerfile.dev` in project root to create the container environment that I used to develop & run & test the project.

If you solve the problem successfully, please let me know how you solved that, I believe that it could help me & others a lot.

**Comment by Bluemoondragon07** [comment]
Thank you so much for your helpful response. I finally got my computer to recognize the command! However, I now get this message:
```
$ yomigana_ebook OmedetakiHito.epub
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\my-user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\yomigana_ebook.exe\__main__.py", line 4, in <module>
  File "C:\Users\my-user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yomigana_ebook\cli.py", line 6, in <module>
    from yomigana_ebook.process_ebook import process_ebook
  File "C:\Users\my-user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yomigana_ebook\process_ebook.py", line 7, in <module>
    from yomigana_ebook.yomituki import yomituki
  File "C:\Users\my-user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yomigana_ebook\yomituki.py", line 4, in <module>
    from fugashi import Tagger  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\my-user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fugashi\__init__.py", line 1, in <module>
    from .fugashi import *
ImportError: DLL load failed while importing fugashi: The specified module could not be found.
```

I deleted the folder and re-cloned the repo, added this line: `$ pip install yomigana-ebook`, did `$ pip install .`, and downloaded unidic. The same message also appears when I use `$ python -m yomigana_ebook.cli` .

I also updated pip. My computer is also a Windows 11, so hopefully that isn't interfering with the script.

**Comment by rabbit19981023** [comment]
Thank you for the updated information.

Firstly, I'm so sorry that I made a stupid mistake again (please forgive me).

The installation process should be like this:

```
$ git clone https://github.com/rabbit19981023/yomigana-ebook.git
$ pip install ./yomigana-ebook
$ python -m unidic download
$ yomigana_ebook <your-ebooks>
```

However, when following the steps above, you would probably face the first problem: `'yomigana_ebook' is not recognized as an internal or external command, operable program or batch file.` ( This means you were right at first time, while the previous comment was wrong😅 )

The problem occured is because you probably used the global python/pip environment to install the python projects/packages, and the installed executable commands still cannot be found becuase they're not in `$PATH` to make Windows to find them.

To allow Windows to find the executables and run them, you need to add the directory where the executable is located to the `$PATH`, which is not recommended. ( `$PATH` is one of the OS environment variable, for more information, please see [adding-a-directory-to-the-path-environment-variable-in-windows](https://stackoverflow.com/questions/9546324/adding-a-directory-to-the-path-environment-variable-in-windows) )

However, if you add the executable directory to `$PATH`, you would get the error message again: `ImportError: DLL load failed while importing fugashi: The specified module could not be found.`.

This is probably a bug in Windows. ( for more information, please see polm/fugashi#42 ).

To solve the problem, please use the `virtualenv`. ( in simple words, it's an isolated environment for a python project to manage python/pip versions and project dependencies ).

You could follow the steps below which creates the `virtualenv` and install the `yomigana-ebook` project:

```
$ git clone https://github.com/rabbit19981023/yomigana-ebook.git

# get into the project directory
$ cd yomigana-ebook

# creates the virtualenv for the python project: yomigana-ebook.
# the virtualenv will be named as .venv, it's just a naming convention.
$ python -m venv .venv

# get into the virtualenv (the command varies for different OS)
# for cmd:
$ .venv\Scripts\activate

# for powershell:
# due to some security reasons, powershell disabled unknown executables by default
# so we need to ask powershell to enable it (only for this session, everytime you open the powershell, you have to manually enable it again)
$ Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process
$ .venv\Scripts\Activate.ps1

# you can install the project now
$ pip install .

$ python -m unidic download
$ yomigana_ebook <your-ebooks>
```

After all the processes you did with the project, you could **leave** the `virtualenv` by just one command:

```
$ deactivate
```

And I always recommend installing python projects/packages in a separate `virtualenv`, if you install them all globally it could easily lead to conflicts and errors.

Hopefully this time could solve all the problems, and start enjoying the converted ebooks!

**Comment by Bluemoondragon07** [comment]
I used the `virtualenv` and it works now! Thank you so much; you've made an amazing tool!  😀
